print "The UNIX Philosophy, by Mike Gancarz"
print ""
print "Small is beautiful."
print "Make each program do one thing well."
print "Build a prototype as soon as possible."
print "Choose portability over efficiency."
print "Store data in flat text files."
print "Use software leverage to your advantage."
print "Use shell scripts to increase leverage and portability."
print "Avoid captive user interfaces."
print "Make every program a filter."
